-- begin PNRSERVICES_SM160_LOG_OPERATIONS
alter table PNRSERVICES_SM160_LOG_OPERATIONS add constraint FK_PNRSERVICES_SM160_LOG_OPERATIONS_ON_LOG foreign key (LOG_ID) references PNRSERVICES_SM160_LOG(ID)^
create index IDX_PNRSERVICES_SM160_LOG_OPERATIONS_ON_LOG on PNRSERVICES_SM160_LOG_OPERATIONS (LOG_ID)^
-- end PNRSERVICES_SM160_LOG_OPERATIONS
-- begin PNRSERVICES_SM160_LOG_DISCOVERY
alter table PNRSERVICES_SM160_LOG_DISCOVERY add constraint FK_PNRSERVICES_SM160_LOG_DISCOVERY_ON_LOG foreign key (LOG_ID) references PNRSERVICES_SM160_LOG(ID)^
create index IDX_PNRSERVICES_SM160_LOG_DISCOVERY_ON_LOG on PNRSERVICES_SM160_LOG_DISCOVERY (LOG_ID)^
-- end PNRSERVICES_SM160_LOG_DISCOVERY
-- begin PNRSERVICES_SM160_LOG
create unique index IDX_PNRSERVICES_SM160_LOG_UNIQ_IP on PNRSERVICES_SM160_LOG (ip) where DELETE_TS is null ^
-- end PNRSERVICES_SM160_LOG
